package com.abel.app.b2b.model.response;

import java.io.Serializable;

public class CompanyLabel implements Serializable {

    //public String Agreement,Asset,Billing,Certification,Charge;

  /*  public String General,
            CRM,
            Customer,
            Corporate,
            Insurance,
            Estimate,
            Reservation,
            Agreement,
            DateOfBirth,
            PhoneNo,
            CheckOut,
            CheckIn,
            Vehicle,
            Rate,
            VINNumber,
            LicenseNo,
            VehicleNo,
            Status,
            VehicleType,
            VehicleCategory,
            License,
            Certification,
            SpecialNote,
            VehicleDamage,
            VehicleTracking,
            Documents,
            CustomRates,
            Miscellaneous,
            SecurityDeposit,
            Deposit,
            Payment,
            Deductible,
            Referral,
            Billing,
            Equipment,
            FlightDetails,
            Inventory,
            Delivery,
            PickUp,
            Tax,
            PolicyNumber,
            VehicleCharges,
            Location,
            DropOffCharges,
            PromotionalCode,
            PromoCode,
            Promo,
            Reimbursement,
            Discount,
            Charge,
            Asset,
            VehicleSuspend,
            Claim,
            Protection,
            Miles;*/
    
    public String General = "General",
    CRM = "CRM",
    Customer= "Customer",
    Corporate= "Corporate",
    Insurance= "Insurance",
    Estimate= "Estimate",
    Reservation= "Booking",
    Agreement= "Agreement",
    DateOfBirth= "Date of Birth",
    PhoneNo= "Phone No",
    CheckOut= "Check Out",
    CheckIn= "Check In",
    Vehicle= "Vehicle",
    Rate= "Rate",
    VINNumber= "VIN Number",
    LicenseNo= "License No",
    VehicleNo= "Vehicle No",
    Status= "Status",
    VehicleType= "Vehicle Type",
    VehicleCategory= "Vehicle Category",
    License= "License",
    Certification= "Certification",
    SpecialNote= "SpecialNote",
    VehicleDamage= "Vehicle Damage",
    VehicleTracking= "Vehicle Tracking",
    Documents= "Documents",
    CustomRates= "Custom Rates",
    Miscellaneous= null,
    SecurityDeposit= "Security Deposit",
    Deposit= "Deposit",
    Payment= "Payment",
    Deductible= "Deductible",
    Referral= "Referral",
    Billing= "Billing",
    Equipment= "Equipment",
    FlightDetails= "Flight Details",
    Inventory= "Inventory",
    Delivery= "Delivery",
    PickUp= "PickUp",
    Tax= "Tax",
    PolicyNumber= "Policy Number",
    VehicleCharges= "Vehicle Charges",
    Location= "Location",
    DropOffCharges= "Drop off Charges",
    PromotionalCode= "Promotional Code",
    PromoCode= "PromoCode",
    Promo= "Promo",
    Reimbursement= "Reimbursement",
    Discount= "Discount",
    Charge= "Charge",
    Asset= "Asset",
    VehicleSuspend= "Vehicle Suspend",
    Claim= "Claim",
    Protection= "Protection",
    Miles= "Miles";
}
